Add graceful-fs to avoid internalBinding error
With node 10.x I got the following error when running `gulp
--production`

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:137:5)
    at require (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:137:5)
    at require (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/forge/pocket.snapmagic.com/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/forge/pocket.snapmagic.com/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)

Updating graceful-fs manually fixed the issue.